server:
  port: 8081
  servlet:
    context-path: /api/v1/users

spring:
  application:
    name: ticketway-user-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

