server:
  port: 8761

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

spring:
  application:
    name: ticketway-registry-server
  config:
    import: "optional:configserver:http://localhost:8084"

