server:
  port: 8083

spring:
  application:
    name: ticketway-gateway-service
  cloud:
    gateway:
      mvc:
        routes:
          - id: item-service
            uri: lb://ticketway-user-service
            predicates:
              - Path=/api/v1/users/**
#          - id: customer-service
#            uri: lb://SPRINGBOOT-CUSTOMER-SERVICES
#            predicates:
#              - Path=/api/v1/customer/**


eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

